name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: basic-rest
      run: docker build . --file Dockerfile --tag basic-rest:$(date +%s)
